[package]
name = "bittensor-subnet-template"
version = "0.1.0"
edition = "2021"
description = "A template for creating Bittensor subnets"
license = "MIT"

[dependencies]
tokio = { version = "1.41", features = ["full"] }
subxt = "0.38.0"
parity-scale-codec = { version = "3.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
tracing = "0.1"
hex = "0.4"
dirs = "5.0"

[build-dependencies]
tokio = { version = "1.41", features = ["full"] }
subxt-codegen = "0.38"
subxt-metadata = "0.38"
parity-scale-codec = "3.0"
subxt-utils-fetchmetadata = { version = "0.38", features = ["url"] }
